version: '3'
services:
  postgres:
    image: postgres:11.5
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=upload-king-dev
      - POSTGRES_USER=postgres

  fake_s3:
    build:
      context: ../fake_s3
    ports:
      - "4567:4567"